Tweak DB settings:
We cannot remove (most) DB settings from .env, because they're not just used
as Django settings, but these env vars are also needed for other services in
the compose file, like PostgreSQL.

Therefore we keep them in the .env.example, and make sure that the Django
configuration side reflects the fact that some of those settings MUST come
from environment variables.

If an attempt is made to start an instance and those settings missing from
.env, Django will terminate with an appropriate exception:

```
ValueError: Couldn't setup configuration 'core.settings.Prod':
  Value 'DB_HOST' is required to be set as the environment variable 'GEORAMA_DB_HOST'
```